spring.application.name=MediTicket02
# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/mediticket_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

resend.api-key=${RESEND_API_KEY}
resend.from-email=onboarding@resend.dev

# Server Port
server.port=${PORT:8080}

# =========================================================
# EMAIL VERIFICATION
# =========================================================
app.verification.base-url=${APP_VERIFICATION_BASE_URL:http://localhost:8080/api/auth/verify}

# Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# BootStrap
app.bootstrap.admin-key=${BOOTSTRAP_ADMIN_KEY}

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000
app.jwt.invite-expiration-ms=172800000

# =========================================================
# EMPLOYEE INVITE
# =========================================================
app.employee-invite.base-url=${EMPLOYEE_INVITE_BASE_URL:http://localhost:8080/signup/employee}